import { TicketStatus } from "@models/ticket";
import { PaymentAdditionalData, PaymentInitResponse, PaymentMethod } from "@my_types/payments";

/**
 * DTO for creating a new Ticket record.
 * Used when a user books a new ticket for a trip.
 * Fields like `id`, `createdAt`, and `updatedAt` are automatically generated by the system.
 * @interface BookTicketDTO
 * @property {string} userId - User ID who is booking the ticket.
 * @property {number | number[] | null} [seatIds] - Seat ID(s) assigned to this ticket (optional during booking).
 * @property {string | null} [couponIds] - Optional coupon IDs for discount.
 * @property {PaymentMethod} paymentMethodCode - Selected payment gateway code.
 * @property {PaymentAdditionalData} [additionalData] - Optional gateway-specific data (e.g., ipAddress, orderInfo, locale).
 */
export interface BookTicketDTO {
	/** User ID who is booking the ticket */
	userId: string;

	/** Seat ID assigned to this ticket (optional during booking) */
	seatIds?: number | number[] | null;

	couponIds?: string | null;

  	/** Selected payment gateway code */
	paymentMethodCode: PaymentMethod;
	
	/** Optional gateway-specific data (e.g., ipAddress, orderInfo, locale) */
	additionalData?: PaymentAdditionalData;
}

/**
 * Response returned by the booking flow to the client.
 * @interface BookTicketResult
 * @property {number[]} ticketIds - Persisted ticket IDs (status = PENDING until payment completes).
 * @property {string} [paymentUrl] - Redirect URL to the selected payment gateway (if applicable).
 * @property {PaymentInitResponse} [payment] - Compact payment summary.
 */
export interface BookTicketResult {
  /** Persisted ticket IDs (status = PENDING until payment completes) */
  ticketIds: number[];

  /** Redirect URL to the selected payment gateway (if applicable) */
  paymentUrl?: string;

  /** Compact payment summary */
  payment?: PaymentInitResponse;
}

/**
 * DTO for filtering or searching Tickets in GET requests.
 * Used for queries like `/tickets?userId=1&tripId=5&minBasePrice=50&maxFinalPrice=100`.
 * All parameters are optional for flexible searching.
 * @interface GetTicketQueryDTO
 * @property {string} [userId] - Filter by user ID.
 * @property {number} [tripId] - Filter by trip ID.
 * @property {TicketStatus} [status] - Filter by ticket status.
 * @property {number} [minBasePrice] - Minimum base price filter.
 * @property {number} [maxBasePrice] - Maximum base price filter.
 * @property {number} [minFinalPrice] - Minimum final price filter.
 * @property {number} [maxFinalPrice] - Maximum final price filter.
 */
export interface GetTicketQueryDTO {
	/** Filter by user ID */
	userId?: string;

	/** Filter by trip ID */
	tripId?: number;

	/** Filter by ticket status */
	status?: TicketStatus;

	/** Minimum base price filter */
	minBasePrice?: number;

	/** Maximum base price filter */
	maxBasePrice?: number;

	/** Minimum final price filter */
	minFinalPrice?: number;

	/** Maximum final price filter */
	maxFinalPrice?: number;
}


/**
 * Options for querying tickets with filtering, sorting, and pagination.
 * Used by ticket service functions like getUserTickets.
 * @interface TicketQueryOptions
 * @property {TicketStatus} [status] - Filter by ticket status.
 * @property {string} [orderId] - Filter by order ID.
 * @property {number} [seatId] - Filter by seat ID.
 * @property {Date} [dateFrom] - Filter by creation date from.
 * @property {Date} [dateTo] - Filter by creation date to.
 * @property {Date} [updatedFrom] - Filter by last updated date from.
 * @property {Date} [updatedTo] - Filter by last updated date to.
 * @property {number} [minBasePrice] - Filter by minimum base price.
 * @property {number} [maxBasePrice] - Filter by maximum base price.
 * @property {number} [minFinalPrice] - Filter by minimum final price.
 * @property {number} [maxFinalPrice] - Filter by maximum final price.
 * @property {number} [limit] - Limit the number of results.
 * @property {number} [offset] - Offset for pagination.
 * @property {'id' | 'basePrice' | 'finalPrice' | 'status' | 'createdAt' | 'updatedAt'} [sortBy] - Sort by field.
 * @property {"ASC" | "DESC"} [sortOrder] - Sort order.
 * @property {("user" | "seat" | "order" | "payments")[]} [include] - Optional associations to include.
 */
export interface TicketQueryOptions {
	/** Filter by ticket status. */
	status?: TicketStatus;
	/** Filter by order ID. */
	orderId?: string;
	/** Filter by seat ID. */
	seatId?: number;
	/** Filter by creation date from. */
	dateFrom?: Date;
	/** Filter by creation date to. */
	dateTo?: Date;
	/** Filter by last updated date from. */
	updatedFrom?: Date;
	/** Filter by last updated date to. */
	updatedTo?: Date;
	/** Filter by minimum base price. */
	minBasePrice?: number;
	/** Filter by maximum base price. */
	maxBasePrice?: number;
	/** Filter by minimum final price. */
	minFinalPrice?: number;
	/** Filter by maximum final price. */
	maxFinalPrice?: number;
	/** Limit the number of results. */
	limit?: number;
	/** Offset for pagination. */
	offset?: number;
	/** Sort by field. */
	sortBy?: 'id' | 'basePrice' | 'finalPrice' | 'status' | 'createdAt' | 'updatedAt';
	/** Sort order. */
	sortOrder?: "ASC" | "DESC";
	/** Optional associations to include. */
	include?: ("user" | "seat" | "order" | "payments")[];
} 